# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_inflacionthomsonreuters_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='datosUsuarioAnonimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(default='?', max_length=50)),
                ('edad', models.IntegerField(default=0)),
                ('expectativaDeInflacion', models.FloatField(default=0)),
                ('gastoTransporte', models.IntegerField(default=0)),
                ('gastoEducacion', models.IntegerField(default=0)),
                ('gastoVivienda', models.IntegerField(default=0)),
                ('gastoSalud', models.IntegerField(default=0)),
            ],
        ),
    ]
